import jsPDF from "jspdf";

type Section = {
  title: string;
  rows: { label: string; value: string }[];
};

// Cache font data to avoid re-fetching on every report
let fontCache: { regular: string; bold: string } | null = null;

async function loadArabicFonts(): Promise<{ regular: string; bold: string }> {
  if (fontCache) return fontCache;

  const [regularBuf, boldBuf] = await Promise.all([
    fetch("/fonts/IBMPlexSansArabic-Regular.ttf").then((r) => r.arrayBuffer()),
    fetch("/fonts/IBMPlexSansArabic-Bold.ttf").then((r) => r.arrayBuffer()),
  ]);

  function bufToBase64(buf: ArrayBuffer): string {
    const bytes = new Uint8Array(buf);
    let binary = "";
    for (let i = 0; i < bytes.length; i++) {
      binary += String.fromCharCode(bytes[i]!);
    }
    return btoa(binary);
  }

  fontCache = { regular: bufToBase64(regularBuf), bold: bufToBase64(boldBuf) };
  return fontCache;
}

function registerFonts(pdf: jsPDF, fonts: { regular: string; bold: string }) {
  pdf.addFileToVFS("IBMPlexSansArabic-Regular.ttf", fonts.regular);
  pdf.addFont("IBMPlexSansArabic-Regular.ttf", "IBMPlexSansArabic", "normal");
  pdf.addFileToVFS("IBMPlexSansArabic-Bold.ttf", fonts.bold);
  pdf.addFont("IBMPlexSansArabic-Bold.ttf", "IBMPlexSansArabic", "bold");
}

export async function generateReportPDF({
  title,
  subtitle,
  dateRange,
  sections,
  lang = "ar",
}: {
  title: string;
  subtitle?: string;
  dateRange: string;
  sections: Section[];
  lang?: "ar" | "en";
}) {
  const fonts = await loadArabicFonts();
  const pdf = new jsPDF("p", "mm", "a4");
  registerFonts(pdf, fonts);

  const pageW = pdf.internal.pageSize.getWidth();
  const margin = 15;
  const contentEnd = pageW - margin;
  let y = margin;

  const isRTL = lang === "ar";

  // Helper: set Arabic font
  const setArabicFont = (style: "normal" | "bold" = "normal") => {
    pdf.setFont("IBMPlexSansArabic", style);
  };

  // --- Header bar ---
  pdf.setFillColor(10, 22, 40);
  pdf.rect(0, 0, pageW, 28, "F");

  // MIMARIC logo text (always Latin)
  pdf.setTextColor(255, 255, 255);
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.text("MIMARIC", margin, 18);

  // Date range
  pdf.setFontSize(10);
  pdf.setTextColor(16, 120, 64);
  setArabicFont();
  pdf.text(dateRange, contentEnd, 18, { align: "right" });

  y = 38;

  // --- Title ---
  pdf.setTextColor(10, 22, 40);
  pdf.setFontSize(16);
  setArabicFont("bold");
  pdf.text(title, pageW / 2, y, { align: "center" });
  y += 8;

  if (subtitle) {
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    setArabicFont();
    pdf.text(subtitle, pageW / 2, y, { align: "center" });
    y += 8;
  }

  y += 4;

  // --- Sections ---
  sections.forEach((section) => {
    if (y + 20 + section.rows.length * 8 > 280) {
      pdf.addPage();
      y = margin;
    }

    // Section header background
    pdf.setFillColor(242, 244, 247);
    pdf.rect(margin, y, pageW - margin * 2, 8, "F");
    pdf.setTextColor(10, 22, 40);
    pdf.setFontSize(11);
    setArabicFont("bold");
    if (isRTL) {
      pdf.text(section.title, contentEnd - 4, y + 6, { align: "right" });
    } else {
      pdf.text(section.title, margin + 4, y + 6);
    }
    y += 12;

    // Rows
    pdf.setFontSize(10);
    section.rows.forEach((row, idx) => {
      if (y > 275) {
        pdf.addPage();
        y = margin;
      }

      if (idx % 2 === 0) {
        pdf.setFillColor(249, 250, 251);
        pdf.rect(margin, y - 4, pageW - margin * 2, 7, "F");
      }

      setArabicFont();
      if (isRTL) {
        // RTL: label on right, value on left
        pdf.setTextColor(80, 80, 80);
        pdf.text(row.label, contentEnd - 4, y, { align: "right" });
        pdf.setTextColor(10, 22, 40);
        setArabicFont("bold");
        pdf.text(row.value, margin + 4, y);
      } else {
        pdf.setTextColor(80, 80, 80);
        pdf.text(row.label, margin + 4, y);
        pdf.setTextColor(10, 22, 40);
        setArabicFont("bold");
        pdf.text(row.value, contentEnd - 4, y, { align: "right" });
      }
      y += 7;
    });

    y += 6;
  });

  // --- Footer ---
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      `Generated by Mimaric | ${new Date().toLocaleDateString("en-SA")} | Page ${i}/${pageCount}`,
      pageW / 2,
      290,
      { align: "center" },
    );
  }

  pdf.save(`${title.replace(/\s+/g, "_")}.pdf`);
}
