import jsPDF from "jspdf";

type Section = {
  title: string;
  rows: { label: string; value: string }[];
};

export function generateReportPDF({
  title,
  subtitle,
  dateRange,
  sections,
  lang: _lang = "ar",
}: {
  title: string;
  subtitle?: string;
  dateRange: string;
  sections: Section[];
  lang?: "ar" | "en";
}) {
  void _lang; // Reserved for future RTL layout support
  const pdf = new jsPDF("p", "mm", "a4");
  const pageW = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  // Header bar
  pdf.setFillColor(10, 22, 40); // Vision Navy #0A1628
  pdf.rect(0, 0, pageW, 28, "F");
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(18);
  pdf.text("MIMARIC", margin, 18);
  pdf.setFontSize(10);
  pdf.setTextColor(16, 120, 64); // Green #107840
  pdf.text(dateRange, pageW - margin, 18, { align: "right" });

  y = 38;

  // Title
  pdf.setTextColor(10, 22, 40);
  pdf.setFontSize(16);
  pdf.text(title, pageW / 2, y, { align: "center" });
  y += 8;

  if (subtitle) {
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(subtitle, pageW / 2, y, { align: "center" });
    y += 8;
  }

  y += 4;

  // Sections
  sections.forEach((section) => {
    // Check page break
    if (y + 20 + section.rows.length * 8 > 280) {
      pdf.addPage();
      y = margin;
    }

    // Section header
    pdf.setFillColor(242, 244, 247);
    pdf.rect(margin, y, pageW - margin * 2, 8, "F");
    pdf.setTextColor(10, 22, 40);
    pdf.setFontSize(11);
    pdf.text(section.title, margin + 4, y + 6);
    y += 12;

    // Rows
    pdf.setFontSize(10);
    section.rows.forEach((row, idx) => {
      if (y > 275) {
        pdf.addPage();
        y = margin;
      }

      if (idx % 2 === 0) {
        pdf.setFillColor(249, 250, 251);
        pdf.rect(margin, y - 4, pageW - margin * 2, 7, "F");
      }

      pdf.setTextColor(80, 80, 80);
      pdf.text(row.label, margin + 4, y);
      pdf.setTextColor(10, 22, 40);
      pdf.text(row.value, pageW - margin - 4, y, { align: "right" });
      y += 7;
    });

    y += 6;
  });

  // Footer
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(
      `Generated by Mimaric | ${new Date().toLocaleDateString("en-SA")} | Page ${i}/${pageCount}`,
      pageW / 2,
      290,
      { align: "center" }
    );
  }

  pdf.save(`${title.replace(/\s+/g, "_")}.pdf`);
}
